import Head from 'next/head'
import FeaturedCollection from '../components/Collection/featuredCol'

const Home = () => {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FeaturedCollection/>
    </main>
  )
}

export default Home
