import Head from 'next/head'
import styles from  '../styles/Home.module.scss'
import menu from '../components/menu/menu'
import Link from 'next/link'
import FeaturedCollection from '../components/featuredCol/featuredCol'
import Footer from '../components/Footer/Footer'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <div className={styles.container}>
          <div className={styles.row}>
            <Link href='/'><div className={styles.logo}></div></Link>
            <ul className={styles.menu}>
              {menu.map((item:string,itx:number) =>  (
                <Link  key={itx} href={item.toLocaleLowerCase()}><li className={styles.item} key={itx}>{item}</li></Link>
              ))}
            </ul>
            <div className={styles.images}>
              <Link href=''>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className={styles.search} viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
              </Link>
              <Link href=''>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className={styles.cart} viewBox="0 0 16 16">
                  <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                </svg>
              </Link>
            </div>
          </div>
        </div>
      </nav>
      <FeaturedCollection/>
      <footer className={styles.footer}>
          <Footer/>
      </footer>
    </div>
  )
}
