import Head from 'next/head'
import FeaturedCollection from '../components/Collection/featuredCol'
import { GetStaticProps, InferGetStaticPropsType } from 'next'
import prisma from '../../prisma/Client'
import { Products } from '@prisma/client'


export const getServerSideProps: GetStaticProps<{ products: Products[]}> = async (ctx) => {

  const products = await prisma.products.findMany()
  return { props:{ products } }
}

const Home = ({products}: InferGetStaticPropsType<typeof getServerSideProps>) => {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FeaturedCollection data={products}/>
    </main>
  )
}

export default Home
