import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.scss'
import menu from '../menu/menu'
import Image from 'next/image'

export default function Home() {
  return (
    <footer className={styles.footer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.row}>
            <div className={styles.links}>
                <p>Quick links</p>
                <div>
                    {menu.map((item:any,itx:number) => (
                        <Link href={item.link}  key={itx}><li className={styles.link} key={itx}>{item.name}</li></Link>
                    ))}
                </div>
            </div>
            <div className={styles.info}>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                     Quas laboriosam ex quis sequi deserunt nobis molestias nisi repudiandae,
                     sed, enim perferendis adipisci eveniet quisquam dicta,
                      debitis ut dolorem ratione dolorum.
                </p>
            </div>
            <div className={styles.img}>
                <Image src='https://cdn.shopify.com/s/files/1/0684/1457/0804/files/pexels-vinicius-neves-6440487.jpg?v=1668867701&width=190' alt='img'></Image>
            </div>
        </div>
      </div>
    </footer>
  )
}